spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_task_management_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
server:
  port: 8080


